gui:
  commitHashLength: 6 # default: 8
  # showDivergenceFromBaseBranch: arrowAndNumber
  authorColors:
    "noidilin": "#c0baad"
    "*": "#878787"
  theme:
    activeBorderColor: # Border color of focused window
      - "#9d9d9d"
      - bold
    inactiveBorderColor: # Border color of non-focused windows
      - "#5d5d5d"
    searchingActiveBorderColor: # Border color of focused window when searching in that window
      - "#faf5eb"
      - bold
    optionsTextColor: # Color of keybindings help text in the bottom line
      - "#4e4e4e"
    selectedLineBgColor: # Background color of selected line.
      - "#2a2a2a"
    inactiveViewSelectedLineBgColor: # Background color of selected line when view doesn't have focus.
      - bold
    cherryPickedCommitFgColor: # Foreground color of copied commit
      - "#dad5c8"
    cherryPickedCommitBgColor: # Background color of copied commit
      - "#414141"
    markedBaseCommitFgColor: # Foreground color of marked base commit (for rebase)
      - "#faf5eb"
    markedBaseCommitBgColor: # Background color of marked base commit (for rebase)
      - "#5d5d5d"
    unstagedChangesColor: # Color for file with unstaged changes
      - red
    defaultFgColor: # Default text color
      - "#878787"
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
