# [env]
# RUSTUP_TOOLCHAIN = "stable-gnu"

[tools]
# bun 1.3.0 bahaves weird on windows device 
bun = "1.3.1"
node = { version = "lts", postinstall = "corepack enable" }
python = "latest"
# uv = "latest" # still not supported by mise core yet, managed with scoop by now

[tools."rust"]
version = "stable-gnu"
profile = "minimal"
# targets = "x86_64-pc-windows-gnu, aarch64-apple-darwin, x86_64-unknown-linux-gnu"

[settings]
experimental = true
python.uv_venv_auto = true # use the virtual environment created by uv
